#pragma once

#define SV_PLATFORM_WINDOWS


#ifdef SV_PLATFORM_WINDOWS 
	#define NULL			0
	#define NULL_PTR		nullptr
	#define EMPTY_STR		"" 

	#define UNDEF_PTR		NULL_PTR
	#define UNDEF_STR		EMPTY_STR
#endif

#define UNDEF_SMARTPTR		NULL
#define UNDEF_STD_VECTOR	NULL

#define UNDEF_INT			NULL
#define UNDEF_INT32			NULL
#define UNDEF_INT64			NULL
#define UNDEF_UINT			NULL
#define UNDEF_UINT32		NULL
#define UNDEF_UINT64		NULL

#define UNDEF_BOOL			0

#define UNDEF_FLOAT			0.0f
#define UNDEF_LFLOAT		UNDEF_FLOAT
#define UNDEF_LLFLOAT		UNDEF_FLOAT

#define UNDEF_VECTOR2F		{ UNDEF_FLOAT, UNDEF_FLOAT }
#define UNDEF_VECTOR2U		{ UNDEF_UINT, UNDEF_INT }
#define UNDEF_VECTOR2V2F	{ UNDEF_VECTOR2F, UNDEF_VECTOR2F }
#define UNDEF_VECTOR2V2UI	{ UNDEF_VECTOR2U, UNDEF_VECTOR2U }		

